service: existence-db

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  api:
    handler: index.api
    memorySize: 128
    description: Generic api
    events:
      - http:
          path: api
          method: get
